version: "3.8"

services:
  web:
    build: ./
    image: &web eubmstu
    container_name: eubmstu
    command: sh -c "python manage.py makemigrations; python manage.py migrate; python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=eubmstu
      - POSTGRES_PASSWORD=eubmstu
      - POSTGRES_DB=eubmstu
    ports:
      - 5432:5432

  rabbit:
    image: library/rabbitmq:3.8-management
    container_name: eubmstu-rabbit
    hostname: eubmstu
    env_file:
      - .env.dev
    ports:
      - 15672:15672
      - 5672:5672

  celery:
    image: *web
    container_name: eubmstu-celery
    env_file:
      - .env.dev
    command: celery -A eubmstu worker
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbit
      - db
    links:
      - rabbit
      - db

  celery_beat:
    image: *web
    container_name: eubmstu-celery_beat
    env_file:
      - .env.dev
    command: celery -A eubmstu beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler --pidfile=/tmp/celeryd.pid
    volumes:
      - ./:/usr/src/app
    depends_on:
      - rabbit
      - db
    links:
      - rabbit
      - db

volumes:
  postgres_data: