version: "3.3"

services:
  web:
    build:
      context: ./
      cache_from:
        - "${WEB_IMAGE}"
    image: "${WEB_IMAGE}"
    container_name: eubmstu
    volumes:
      - static_volume:/static
      - media_volume:/usr/src/app/mediafiles
    expose:
      - 8000
    env_file:
      - .env

#  celery:
#    image: "${WEB_IMAGE}"
#    container_name: eubmstu-celery
#    env_file:
#      - .env
#    command: celery -A eubmstu worker
#    depends_on:
#      - web

#  celery_beat:
#    image: "${WEB_IMAGE}"
#    container_name: eubmstu-celery_beat
#    env_file:
#      - .env
#    command: celery -A eubmstu beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#    depends_on:
#      - web

volumes:
  static_volume:
  media_volume: