# Generated by Django 2.2.1 on 2019-05-15 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название отчёта')),
                ('settings', models.CharField(max_length=200, verbose_name='Параметры отчёта')),
                ('date', models.DateTimeField(verbose_name='Дата создания отчёта')),
                ('link', models.CharField(max_length=200, verbose_name='Ссылка для скачивания отчёта')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'отчёт',
                'verbose_name_plural': 'Отчёты',
                'ordering': ['date'],
            },
        ),
    ]
