# Generated by Django 2.2 on 2019-05-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0009_auto_20190505_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'пользователя', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
