# Generated by Django 2.2.1 on 2019-05-15 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_auto_20190514_2312'),
        ('authentication', '0012_auto_20190511_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='work',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.Subdepartament'),
        ),
    ]
