# Generated by Django 2.2.1 on 2019-05-15 10:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0014_auto_20190515_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subdepartament', verbose_name='Место работы'),
        ),
    ]
