# Generated by Django 3.2.4 on 2021-06-23 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0015_auto_20190515_1318'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(help_text='Обязательное поле', max_length=150, verbose_name='first name'),
        ),
    ]
