# Generated by Django 2.2 on 2019-05-05 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0002_auto_20190505_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='semester',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Semester', verbose_name='Семестр'),
        ),
        migrations.AlterField(
            model_name='group',
            name='subdepartament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subdepartament', verbose_name='Кафедра'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='progress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='session',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterField(
            model_name='studentsgroup',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Group', verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='studentsgroup',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Student', verbose_name='Студент'),
        ),
        migrations.AlterField(
            model_name='subdepartament',
            name='departament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Departament', verbose_name='Факультет'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='subdepartament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subdepartament', verbose_name='Кафедра'),
        ),
    ]
