# Generated by Django 2.2 on 2019-05-05 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0003_auto_20190505_2236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='type_rating',
            field=models.CharField(choices=[('Кур', 'Курсовая'), ('Зач', 'Зачёт'), ('Экз', 'Экзамен'), ('Прк', 'Практика'), ('РЭ', 'Рейтинговый экзамен'), ('НРС', 'НРС')], max_length=5, verbose_name='Тип оценки'),
        ),
    ]
