# Generated by Django 2.2 on 2019-05-05 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0004_auto_20190505_2241'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'ordering': ['code'], 'verbose_name': 'Факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'Группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Текущая успеваемость'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'Семестр', 'verbose_name_plural': 'Семестры'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Результаты сессии'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['gradebook'], 'verbose_name': 'Студент', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='studentsgroup',
            options={'ordering': ['group'], 'verbose_name': 'СтудентыГруппы'},
        ),
        migrations.AlterModelOptions(
            name='subdepartament',
            options={'ordering': ['code'], 'verbose_name': 'Кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
