# Generated by Django 2.2 on 2019-05-05 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0005_auto_20190505_2246'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'verbose_name': 'Текущая успеваемость', 'verbose_name_plural': 'Текущая успеваемость'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'verbose_name': 'Результаты сессии', 'verbose_name_plural': 'Результаты сессии'},
        ),
        migrations.AlterModelOptions(
            name='studentsgroup',
            options={'ordering': ['group'], 'verbose_name': 'СтудентыГруппы', 'verbose_name_plural': 'СтудентыГруппы'},
        ),
    ]
