# Generated by Django 2.2 on 2019-05-05 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0007_auto_20190505_2249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'ordering': ['code'], 'verbose_name': 'факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['name'], 'verbose_name': 'группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='semester',
            options={'verbose_name': 'семестр', 'verbose_name_plural': 'Семестры'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['gradebook'], 'verbose_name': 'студента', 'verbose_name_plural': 'Студенты'},
        ),
        migrations.AlterModelOptions(
            name='subdepartament',
            options={'ordering': ['code'], 'verbose_name': 'кафедру', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'предмет', 'verbose_name_plural': 'Предметы'},
        ),
    ]
