# Generated by Django 2.2 on 2019-05-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0008_auto_20190505_2250'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StudentsGroup',
        ),
    ]
