# Generated by Django 2.2 on 2019-05-05 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0009_delete_studentsgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='students',
            field=models.ManyToManyField(to='control.Student'),
        ),
    ]
