# Generated by Django 2.2.1 on 2019-05-11 19:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_auto_20190511_2108'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semester',
            name='current',
        ),
    ]
