# Generated by Django 2.2.1 on 2019-05-11 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_remove_semester_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='code',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='Код'),
        ),
    ]
