# Generated by Django 2.2.1 on 2019-05-11 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0014_auto_20190511_2312'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['name'], 'verbose_name': 'семестр', 'verbose_name_plural': 'Семестры'},
        ),
        migrations.AddField(
            model_name='departament',
            name='number',
            field=models.IntegerField(null=True),
        ),
    ]
