# Generated by Django 2.2.1 on 2019-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0016_auto_20190512_0050'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'ordering': ['number'], 'verbose_name': 'факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.AlterField(
            model_name='departament',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Порядкоый номер на сайте'),
        ),
    ]
