# Generated by Django 2.2.1 on 2019-05-12 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0017_auto_20190512_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departament',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Порядковый номер на сайте'),
        ),
    ]
