# Generated by Django 2.2.1 on 2019-05-12 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0018_auto_20190512_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartament',
            name='number',
            field=models.IntegerField(null=True, unique=True, verbose_name='Порядковый номер на сайте'),
        ),
    ]
