# Generated by Django 2.2.1 on 2019-05-12 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0019_subdepartament_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartament',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Название кафедры'),
        ),
        migrations.AlterUniqueTogether(
            name='subdepartament',
            unique_together={('code', 'name')},
        ),
    ]
