# Generated by Django 2.2.1 on 2019-05-12 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0020_auto_20190512_1645'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdepartament',
            options={'ordering': ['code'], 'verbose_name': 'кафедра', 'verbose_name_plural': 'Кафедры'},
        ),
        migrations.AlterField(
            model_name='subdepartament',
            name='number',
            field=models.IntegerField(null=True, verbose_name='Порядковый номер на сайте'),
        ),
    ]
