# Generated by Django 2.2.1 on 2019-05-12 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0021_auto_20190512_1656'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='semester',
            options={'ordering': ['code'], 'verbose_name': 'семестр', 'verbose_name_plural': 'Семестры'},
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=10, verbose_name='Название группы'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'code_link')},
        ),
    ]
