# Generated by Django 2.2.1 on 2019-05-12 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0022_auto_20190512_1858'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='code_link',
            new_name='code',
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'code')},
        ),
    ]
