# Generated by Django 2.2.1 on 2019-05-12 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0023_auto_20190512_1912'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departament',
            options={'ordering': ['code'], 'verbose_name': 'факультет', 'verbose_name_plural': 'Факультеты'},
        ),
        migrations.RemoveField(
            model_name='departament',
            name='number',
        ),
        migrations.RemoveField(
            model_name='subdepartament',
            name='number',
        ),
    ]
