# Generated by Django 2.2.1 on 2019-05-13 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0027_auto_20190512_2340'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.RemoveField(
            model_name='semester',
            name='session',
        ),
    ]
