# Generated by Django 2.2.1 on 2019-05-13 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0028_auto_20190513_1249'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'ordering': ['subdepartament'], 'verbose_name': 'группа', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterField(
            model_name='group',
            name='code',
            field=models.CharField(max_length=50, verbose_name='Код группы для сайта'),
        ),
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('name', 'code', 'semester')},
        ),
    ]
