# Generated by Django 2.2.1 on 2019-05-13 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0029_auto_20190513_1314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='isEmpty',
            field=models.BooleanField(default=False, verbose_name='Данных в ЕУ нет'),
        ),
    ]
