# Generated by Django 2.2.1 on 2019-05-13 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0031_auto_20190514_0136'),
    ]

    operations = [
        migrations.AlterIndexTogether(
            name='group',
            index_together=set(),
        ),
    ]
