# Generated by Django 2.2.1 on 2019-05-14 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0032_auto_20190514_0141'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subdepartament',
            name='code',
            field=models.CharField(max_length=11, unique=True, verbose_name='Код кафедры'),
        ),
    ]
