# Generated by Django 2.2.1 on 2019-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0033_auto_20190514_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gradebook',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер зачётной книжки'),
        ),
    ]
