# Generated by Django 2.2.1 on 2019-05-17 09:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0034_auto_20190515_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.Semester', verbose_name='Семестр'),
        ),
        migrations.AddField(
            model_name='session',
            name='semester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='control.Semester', verbose_name='Семестр'),
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together={('name', 'subdepartament')},
        ),
    ]
