# Generated by Django 2.2.1 on 2019-05-26 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0035_auto_20190517_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='isStudying',
            field=models.BooleanField(default=True, verbose_name='Обучается ли сейчас студент'),
        ),
    ]
