# Generated by Django 2.2.1 on 2019-06-05 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0037_auto_20190605_1458'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Group', verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'группаПредмет',
                'verbose_name_plural': 'ГруппыПредметы',
            },
        ),
        migrations.RemoveField(
            model_name='subject',
            name='groups',
        ),
        migrations.AlterField(
            model_name='progress',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.GroupSubject', verbose_name='Предмет'),
        ),
        migrations.AddField(
            model_name='groupsubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.Subject', verbose_name='Предмет'),
        ),
        migrations.AlterUniqueTogether(
            name='groupsubject',
            unique_together={('group', 'subject')},
        ),
    ]
