# Generated by Django 2.2.1 on 2019-06-05 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0038_auto_20190605_2042'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='progress',
            options={'ordering': ['student'], 'verbose_name': 'Текущая успеваемость', 'verbose_name_plural': 'Текущая успеваемость'},
        ),
    ]
