# Generated by Django 2.2.1 on 2019-06-08 20:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0039_auto_20190605_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='control.GroupSubject', verbose_name='Предмет'),
        ),
    ]
