# Generated by Django 2.2.2 on 2019-06-15 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0044_auto_20190615_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='rating',
            field=models.CharField(blank=True, choices=[('Зчт', 'Зачтено'), ('Нзч', 'Не зачтено'), ('Отл', 'Отлично'), ('Хор', 'Хорошо'), ('Удов', 'Удовлетворительно'), ('НА', 'Не аттестован'), ('Я', 'Неявка'), ('Напр', 'Направление'), ('Неуд', 'Неудовлетворительно')], max_length=4, null=True, verbose_name='Оценка'),
        ),
    ]
