# Generated by Django 3.2.4 on 2021-06-23 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0051_subdepartament_prove'),
    ]

    operations = [
        migrations.AddField(
            model_name='semester',
            name='session',
            field=models.IntegerField(blank=True, null=True, verbose_name='Код для сессии'),
        ),
    ]
