# Generated by Django 3.2.4 on 2021-06-23 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0052_semester_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='guid',
            field=models.UUIDField(blank=True, null=True, verbose_name='ID студента в системе'),
        ),
    ]
