# Generated by Django 3.2.4 on 2021-06-30 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0053_student_guid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=500, verbose_name='Название'),
        ),
    ]
