# Generated by Django 3.2.4 on 2021-07-08 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0054_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='session',
            name='rating',
            field=models.CharField(blank=True, choices=[('Зчт', 'Зачтено'), ('Нзч', 'Не зачтено'), ('Отл', 'Отлично'), ('Хор', 'Хорошо'), ('Удов', 'Удовлетворительно'), ('НА', 'Не аттестован'), ('Я', 'Неявка'), ('Напр', 'Направление'), ('Неуд', 'Неудовлетворительно'), ('Дк', 'Дк'), ('Д', 'Дисциплина'), ('П', 'Подготовка')], max_length=4, null=True, verbose_name='Оценка'),
        ),
    ]
