# Generated by Django 3.2.4 on 2021-07-21 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0056_rename_guid_student_uuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='levelEducation',
            field=models.CharField(choices=[('bachelor', 'Бакалавриат'), ('magister', 'Магистратура'), ('specialist', 'Специалитет / Аспирантура'), ('archive', 'Архивные записи')], max_length=10, null=True, verbose_name='Уровень образования'),
        ),
    ]
