# Generated by Django 3.2.4 on 2021-07-22 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0057_alter_group_leveleducation'),
        ('control', '0057_auto_20210721_2124'),
    ]

    operations = [
    ]
